### ISSUE TITLE
TESTING

### ISSUE THREAD

**Issue by jstockwin** [jstockwin/EpiEstimApp#8]
There is a lot of testing which should happen. This issue is pretty blank for now but should be updated to add places in need of testing.

It may also be worth looking into automated unit/end2end testing. I don't know how easy this is in R, or if it's even worth it. 

# TODO
## Suite 001 - Basic
- [x] Write connection test
## Suite 002 - States
- [x] Write tests for state 1.1
- [x] Write tests for state 2.1
- [x] Write tests for state 2.2
- [x] Write tests for state 3.1
- [x] Write tests for state 4.1
- [x] Write tests for state 5.1
- [x] Write tests for state 6.1
- [x] Write tests for state 6.2
- [x] Write tests for state 7.1
- [x] Write tests for state 7.2
- [x] Write tests for state 7.3
- [x] Write tests for state 7.4
- [x] Write tests for state 8.1
- [x] Write tests for state 8.2
- [x] Write tests for state 8.3
- [x] Write tests for state 8.4
- [x] Write tests for state 8.5
- [x] Write tests for state 9.1
- [x] Write tests for state 9.2
- [x] Write tests for state 9.3

### Suite 03 - Error checks
- [x] Write tests for state 1.1
- [x] Write tests for state 2.1
- [x] Write tests for state 2.2
- [x] Write tests for state 3.1
- [x] Write tests for state 4.1
- [x] Write tests for state 5.1
- [x] Write tests for state 6.1
- [x] Write tests for state 6.2
- [x] Write tests for state 7.1
- [x] Write tests for state 7.2
- [x] Write tests for state 7.3
- [x] Write tests for state 7.4
- [x] Write tests for state 8.1
- [x] Write tests for state 8.2
- [x] Write tests for state 8.3
- [x] Write tests for state 8.4
- [x] Write tests for state 8.5
- [x] Write tests for state 9.1
- [x] Write tests for state 9.2
- [x] Write tests for state 9.3
## Suite 004 - End to end (e2e) tests
- [x] Write tests to compare runs with different incidence data
- [x] Write tests to compare runs with endpoint 8.1: `SIFromSample (preloaded)`
- [x] Write tests to compare runs with endpoint 9.1: `SIFromData`
- [x] Write tests to compare runs with endpoint 8.3: `SIFromSample (uploaded)`
- [x] Write tests to compare runs with endpoint 7.3: `UncertainSI`
- [x] Write tests to compare runs with endpoint 8.4: `ParametricSI`
- [x] Write tests to compare runs with endpoint 9.2: `NonParametricSI (uploaded)`
- [x] Write tests to compare runs with endpoint 9.3:`NonParametricSI (preloaded)`

**Comment by jstockwin** [comment]
As an update, I am very much in the middle of writing tests with testthat and RSelenium. Here's the TODO, which should be kept updated:
# TODO
## Suite 001 - Basic
- [ ] Write connection test
## Suite 002 - States
- [ ] Write tests for state 1.1
- [ ] Write tests for state 2.1
- [ ] Write tests for state 2.2
- [ ] Write tests for state 3.1
- [ ] Write tests for state 4.1
- [ ] Write tests for state 5.1
- [ ] Write tests for state 6.1
- [ ] Write tests for state 6.2
- [ ] Write tests for state 7.1
- [ ] Write tests for state 7.2
- [ ] Write tests for state 7.3
- [ ] Write tests for state 7.4
- [ ] Write tests for state 8.1
- [ ] Write tests for state 8.2
- [ ] Write tests for state 8.3
- [ ] Write tests for state 8.4
- [ ] Write tests for state 8.5
- [ ] Write tests for state 9.1
- [ ] Write tests for state 9.2
- [ ] Write tests for state 9.3

### Suite 03 - Error checks
- [ ] Write tests for state 1.1
- [ ] Write tests for state 2.1
- [ ] Write tests for state 2.2
- [ ] Write tests for state 3.1
- [ ] Write tests for state 4.1
- [ ] Write tests for state 5.1
- [ ] Write tests for state 6.1
- [ ] Write tests for state 6.2
- [ ] Write tests for state 7.1
- [ ] Write tests for state 7.2
- [ ] Write tests for state 7.3
- [ ] Write tests for state 7.4
- [ ] Write tests for state 8.1
- [ ] Write tests for state 8.2
- [ ] Write tests for state 8.3
- [ ] Write tests for state 8.4
- [ ] Write tests for state 8.5
- [ ] Write tests for state 9.1
- [ ] Write tests for state 9.2
- [ ] Write tests for state 9.3
## Suite 004 - Full test runs
- [ ] Write tests to compare runs with endpoint 8.1: `SIFromSample (preloaded)` (preloaded incidence)
- [ ] Write tests to compare runs with endpoint 8.1: `SIFromSample (preloaded)` (local incidence)
- [ ] Write tests to compare runs with endpoint 8.1: `SIFromSample (preloaded)` (imported incidence)

- [ ] Write tests to compare runs with endpoint 9.1: `SIFromData` (preloaded incidence)
- [ ] Write tests to compare runs with endpoint 9.1: `SIFromData` (local incidence)
- [ ] Write tests to compare runs with endpoint 9.1: `SIFromData` (imported incidence)

- [ ] Write tests to compare runs with endpoint 8.3: `SIFromSample (uploaded)` (preloaded incidence)
- [ ] Write tests to compare runs with endpoint 8.3: `SIFromSample (uploaded)` (local incidence)
- [ ] Write tests to compare runs with endpoint 8.3: `SIFromSample (uploaded)` (imported incidence)

- [ ] Write tests to compare runs with endpoint 7.3: `UncertainSI` (preloaded incidence)
- [ ] Write tests to compare runs with endpoint 7.3: `UncertainSI` (local incidence)
- [ ] Write tests to compare runs with endpoint 7.3: `UncertainSI` (imported incidence)

- [ ] Write tests to compare runs with endpoint 8.4: `ParametricSI` (preloaded incidence)
- [ ] Write tests to compare runs with endpoint 8.4: `ParametricSI` (local incidence)
- [ ] Write tests to compare runs with endpoint 8.4: `ParametricSI` (imported incidence)

- [ ] Write tests to compare runs with endpoint 9.2: `NonParametricSI (uploaded)` (preloaded incidence)
- [ ] Write tests to compare runs with endpoint 9.2: `NonParametricSI (uploaded)` (local incidence)
- [ ] Write tests to compare runs with endpoint 9.2: `NonParametricSI (uploaded)` (imported incidence)

- [ ] Write tests to compare runs with endpoint 9.3:`NonParametricSI (preloaded)` (preloaded incidence)
- [ ] Write tests to compare runs with endpoint 9.3: `NonParametricSI (preloaded)` (local incidence)
- [ ] Write tests to compare runs with endpoint 9.3: `NonParametricSI (preloaded)` (imported incidence)

**Comment by jstockwin** [comment]
This will be useful if/when our tests start to take more than 10 minutes to complete:
https://github.com/travis-ci/travis-ci/issues/3849#issuecomment-255096774
